
export const data = [
  
    {
        date: "2023-04",
        abdominals: 2,
        neck: 3,
        abductors: 1,
        forearms: 4,
        glutes: 2,
        hamstrings: 2,
        lats: 3,
        biceps: 2,
        calves: 3,
        chest: 1,
        lower_back: 1,
        middle_back: 2,
        quadriceps:2,
        traps: 3,
        triceps: 1
      },
      {
        date: "2023-03",
        abdominals: 4,
        abductors: 6,
        biceps: 2,
        calves: 5,
        chest: 1,
        forearms: 4,
        glutes: 2,
        hamstrings: 2,
        neck: 0,
        quadriceps:1,
        lats: 3,
        lower_back: 2,
        middle_back: 1,
        traps: 3,
        triceps: 1
      },
      {
        date: "2023-02",
        abdominals: 4,
        abductors: 0,
        biceps: 2,
        calves: 5,
        chest: 1,
        forearms: 4,
        glutes: 1,
        hamstrings: 2,
        lats: 3,
        lower_back: 0,
        middle_back: 1,
        neck: 0,
        quadriceps:1,
        traps: 3,
        triceps: 1
      },
    
      {
        date: "2023-06",
        calves: 5,
        chest: 1,
        forearms: 6,
        glutes: 1,
        hamstrings: 2,
        lats: 3,
        lower_back: 0,
        abdominals: 6,
        abductors: 0,
        biceps: 2,
        middle_back: 1,
        neck: 0,
        quadriceps:1,
        traps: 3,
        triceps: 1
      },
      ]
